language: android

android:
  components:
    - build-tools-24.0.2
    - android-23
    - extra-android-m2repository
    - extra-android-support

jdk: oraclejdk8

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle

script: ./gradlew build test